// Generated by tools/update_taiwan_calendar.py; do not edit.
// Source: DGPA via https://allen0099.github.io/taiwan-calendar/
// Open Government Data License 1.0; see licenses/TaiwanCalendar-NOTICE.md.
#pragma once
#include <cstdint>
struct TaiwanCalendarYear { int year; uint32_t workdays[12]; };
static constexpr TaiwanCalendarYear TAIWAN_CALENDAR[] = {
    {2026, {0x3e7cf9f2U, 0x03c01f3eU, 0x67cf9f3eU, 0x3cf9f3c3U, 0x1f3e7cf8U, 0x33e3cf9fU, 0x7cf9f3e7U, 0x4f9f3e7cU, 0x30f3e7cfU, 0x3c7cf8f3U, 0x27cf9f3eU, 0x78f3e7cfU}},
    {2027, {0x1f3e7cf8U, 0x03e7cc07U, 0x73e7cf9eU, 0x1e7cf9c3U, 0x4f9f3e7cU, 0x39f3e6cfU, 0x3e7cf9f3U, 0x67cf9f3eU, 0x34f9b3e7U, 0x1e3e78f9U, 0x33e7cf9fU, 0x3c79f3e7U}},
};
constexpr int TAIWAN_CALENDAR_FIRST_YEAR=2026, TAIWAN_CALENDAR_LAST_YEAR=2027;
