"""Generate the embedded 4-bit Noto TC / Chakra Petch / Orbitron glyph subset."""
import argparse
import math
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("font", type=Path, help="Noto Sans TC variable font for Chinese")
    parser.add_argument("--latin-font", type=Path, required=True, help="Chakra Petch Medium for small ASCII")
    parser.add_argument("--display-font", type=Path, required=True, help="Orbitron variable font for large ASCII")
    args = parser.parse_args()
    source = (ROOT / "components/display/ui_renderer.cpp").read_text(encoding="utf-8")
    chars = sorted(set(chr(i) for i in range(32, 127)) | {c for c in source if ord(c) > 127})
    data, glyphs = [], []
    for size in [10, 12, 16, 24, 32]:
        chinese = ImageFont.truetype(str(args.font), size)
        chinese.set_variation_by_axes([600 if size >= 16 else 500])
        latin = ImageFont.truetype(str(args.latin_font), size)
        display = ImageFont.truetype(str(args.display_font), size)
        display.set_variation_by_axes([600])
        for char in chars:
            font = chinese if ord(char) > 127 else display if size >= 24 else latin
            advance = max(1, round(font.getlength(char)))
            if char.isascii() and char.isdigit():
                advance = math.ceil(max(font.getlength(digit) for digit in "0123456789"))
            # Preserve negative bearings, ascenders and right-side overhangs.
            # Crop the quantized ink, storing its offset separately from advance.
            pad = size
            img = Image.new("L", (size * 4, size * 4))
            x = (advance-font.getlength(char))/2 if char.isascii() and char.isdigit() else 0
            ImageDraw.Draw(img).text((pad+x, pad+size-2), char, font=font, fill=255, anchor="ls")
            img = img.point(lambda value: value >> 4)
            bbox = img.getbbox()
            if bbox:
                left, top = bbox[0]-pad, bbox[1]-pad
                img = img.crop(bbox)
            else:
                left = top = 0
                img = Image.new("L", (1, 1))
            width, height = img.size
            assert -128 <= left < 128 and -128 <= top < 128
            assert max(width, height, advance) < 256
            values = list(img.get_flattened_data())
            if len(values) % 2:
                values.append(0)
            offset = len(data)
            data.extend((values[i] << 4) | values[i + 1] for i in range(0, len(values), 2))
            glyphs.append(((size << 21) | ord(char), offset, width, height, advance, left, top))
    out = ["// Generated by tools/generate_font.py; Noto Sans TC / Chakra Petch / Orbitron.",
           "// All source fonts: SIL Open Font License 1.1; see licenses/.",
           "#pragma once", "#include <cstdint>", "#include <cstddef>",
           "struct Glyph { uint32_t key, offset; uint8_t width, height, advance; int8_t left, top; };",
           "static constexpr uint8_t FONT_PIXELS[] = {"]
    out += [",".join(str(v) for v in data[i:i + 32]) + "," for i in range(0, len(data), 32)]
    out += ["};", "static constexpr Glyph FONT_GLYPHS[] = {"]
    out += ["{" + ",".join(map(str, glyph)) + "}," for glyph in glyphs]
    out += ["};", "static constexpr size_t GLYPH_COUNT = sizeof(FONT_GLYPHS)/sizeof(FONT_GLYPHS[0]);"]
    (ROOT / "components/display/font_data.h").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"Generated {len(glyphs)} glyphs, {len(data)} pixel bytes")

if __name__ == "__main__":
    main()
