"""Refresh the embedded Taiwan calendar, or verify it without network access.

python tools/update_taiwan_calendar.py --refresh
python tools/update_taiwan_calendar.py --check
"""
import argparse
import calendar
from concurrent.futures import ThreadPoolExecutor
import hashlib
import json
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
BASE = "https://allen0099.github.io/taiwan-calendar/"
MIN_YEAR = 2026
SNAPSHOT = ROOT / "data/taiwan_calendar.json"
HEADER = ROOT / "components/app_core/taiwan_calendar_data.h"


def parse_year(data, year):
    if type(year) is not int or not MIN_YEAR <= year <= 9999 or data.get("year") != year:
        raise ValueError("Invalid calendar year")
    months = {}
    for entry in data["months"]:
        month = entry["month"]
        if type(month) is not int or not 1 <= month <= 12 or month in months:
            raise ValueError("Invalid or duplicate month")
        count = calendar.monthrange(year, month)[1]
        days = {}
        for item in entry["holidays"]:
            date = item["date"]
            if not isinstance(date, str) or len(date) != 8 or not date.isascii() or not date.isdigit():
                raise ValueError("Invalid date")
            day = int(date[6:])
            if date[:6] != f"{year:04d}{month:02d}" or not 1 <= day <= count or day in days:
                raise ValueError("Mismatched, invalid or duplicate date")
            if type(item["isHoliday"]) is not bool:
                raise ValueError("isHoliday must be boolean")
            # isWeekend is not a work/rest decision: some Saturdays are makeup days.
            days[day] = "0" if item["isHoliday"] else "1"
        if len(days) != count:
            raise ValueError("Calendar does not contain every date")
        months[month] = "".join(days[day] for day in range(1, count + 1))
    if len(months) != 12:
        raise ValueError("Calendar does not contain every month")
    return [months[month] for month in range(1, 13)]


def download(name):
    with urlopen(BASE + name, timeout=30) as response:
        raw = response.read(1024 * 1024 + 1)
    if len(raw) > 1024 * 1024:
        raise ValueError("Calendar response too large")
    return raw


def fetch_year(year):
    raw = download(f"{year}/all.json")
    data = json.loads(raw)
    return dict(year=year, generated_at=data["generatedAt"],
                sha256=hashlib.sha256(raw).hexdigest(), workdays=parse_year(data, year))


def calendar_years(index):
    years = {entry["year"] for entry in index["availableCalendars"]}
    if any(type(year) is not int or not 1900 <= year <= 9999 for year in years):
        raise ValueError("Invalid calendar index")
    years = sorted(year for year in years if year >= MIN_YEAR)
    if not years:
        raise ValueError(f"Calendar index has no years from {MIN_YEAR} onward")
    return years


def make_header(snapshot):
    lines = ["// Generated by tools/update_taiwan_calendar.py; do not edit.",
             "// Source: DGPA via https://allen0099.github.io/taiwan-calendar/",
             "// Open Government Data License 1.0; see licenses/TaiwanCalendar-NOTICE.md.",
             "#pragma once", "#include <cstdint>",
             "struct TaiwanCalendarYear { int year; uint32_t workdays[12]; };",
             "static constexpr TaiwanCalendarYear TAIWAN_CALENDAR[] = {"]
    seen = set()
    for entry in snapshot["years"]:
        year, months = entry["year"], entry["workdays"]
        if type(year) is not int or not MIN_YEAR <= year <= 9999 or year in seen or len(months) != 12:
            raise ValueError("Invalid snapshot year")
        seen.add(year)
        masks = []
        for month, days in enumerate(months, 1):
            if len(days) != calendar.monthrange(year, month)[1] or set(days) - {"0", "1"}:
                raise ValueError("Invalid snapshot month")
            masks.append(sum((char == "1") << day for day, char in enumerate(days)))
        lines.append("    {" + str(year) + ", {" + ", ".join(f"0x{mask:08x}U" for mask in masks) + "}},")
    if not seen:
        raise ValueError("Empty calendar")
    lines += ["};", f"constexpr int TAIWAN_CALENDAR_FIRST_YEAR={min(seen)}, TAIWAN_CALENDAR_LAST_YEAR={max(seen)};"]
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--refresh", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.refresh:
        index = json.loads(download("index.json"))
        years = calendar_years(index)
        with ThreadPoolExecutor(max_workers=4) as pool:
            records = list(pool.map(fetch_year, years))
        snapshot = dict(source=BASE, license="https://data.gov.tw/license", years=records)
        header = make_header(snapshot)  # Validate every year before replacing either output.
        SNAPSHOT.parent.mkdir(parents=True, exist_ok=True)
        SNAPSHOT.write_text(json.dumps(snapshot, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        HEADER.write_text(header, encoding="utf-8")
    else:
        snapshot = json.loads(SNAPSHOT.read_text(encoding="utf-8"))
        if HEADER.read_text(encoding="utf-8") != make_header(snapshot):
            raise SystemExit("Embedded calendar differs from the checked-in snapshot")
    years = [entry["year"] for entry in snapshot["years"]]
    print(f"Taiwan calendar: {min(years)}-{max(years)}, {len(years)*12} complete months")


if __name__ == "__main__":
    main()
